### ISSUE TITLE
Division and multiplication support

### ISSUE THREAD

**Issue by Compro-Prasad** [akatov/pretty-mode#58]
Division(/): ÷
Multiplication(*): ×

**Comment by grettke** [comment]
My gut reaction is that both `/` and `*` are so often used as mathematical operators _and_ delimiters that they haven't been added thus far. They _could_ be added, somehow. What have you pondered on the topic?

**Comment by Compro-Prasad** [comment]
Sorry, for that. Division(/) has been widely accepted and (x) can't be used for multiplication because it represents a character from the alphabet.

**Comment by grettke** [comment]
@Compro-Prasad Thank you for your consideration of pretty-mode! I love (x) because that is what APL uses, but alas... you are right.
