### ISSUE TITLE
"Attempt to shape unibyte text" crash error & `==` is rendered as <blank>

### ISSUE THREAD

**Issue by last-ent** [akatov/pretty-mode#66]
Hello, I was trying to use `pretty-mode` but ran into two issues 

- When I tried to open my C source code file with < 50 lines, the editor would hang with error message, "Attempt to shape unibyte text".

- There is an issue with how it is rendering `==`. In my source code (python) it is being rendered as a blank rectangle similar to `[]`

I am using emacs 27.1, Cascadia Code for ligatures on Ubuntu.

**Comment by grettke** [comment]
Hi @last-ent .

Regarding that error message, I'm not familiar with it and I don't know what could be causing it. However, you can turn on error reporting to collect more important. Call the function `toggle-debug-on-error` and then reproduce the issue. A buffer with a stack trace will probably appear. Study it for information on the source of the error (assuming there is one). Paste it here if it is small or upload a file and we can look at it together.

Regarding the `□` it probably means that your selected font doesn't have a symbol for that character. Did you expect there to be? If have another app using that font can you enter in that character and have it displayed at all? That way you can start to rule out a font issue, or Emacs issue. Let me know. Simplest case: start an Emacs session with nothing loaded `emacs --no-init-file` then configure the font and nothing else and see how that goes too.

**Comment by last-ent** [comment]
Hi @grettke ,

I tried opening the file after enabling `toggle-debug-on-error` but emacs gets frozen with following message. So can't make any headway.
![image](https://user-images.githubusercontent.com/6392541/98592407-f93d8580-22d1-11eb-8672-966eac719de1.png)

> Regarding the □ it probably means that your selected font doesn't have a symbol for that character. 

It works without pretty-mode
![image](https://user-images.githubusercontent.com/6392541/98592791-7ff26280-22d2-11eb-98a3-2fedaad6f530.png)

sadly has issue when I enable it 

![image](https://user-images.githubusercontent.com/6392541/98592816-8b458e00-22d2-11eb-97df-3877efbdec05.png)

**Comment by Alf0nso** [comment]
I have the same problem!! I am using:
1. GNU Emacs 27.1 (build 1, x86_64-w64-mingw32) of 2020-08-21
2. Font: Roboto Mono-14.0

![image](https://user-images.githubusercontent.com/32681068/111160959-851e3180-8592-11eb-8b4c-2167b3ebfd4a.png)
